name: Deploy web

on:
  push:
    branches: ['main']

jobs:
  deploy_web:
    name: Deploy web
    type: deploy
    params:
      prod: true

  notify_slack:
    name: Notify Slack
    needs: [deploy_web]
    type: slack
    params:
      webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
      message: "Web deploy completed for Crowdia"
